/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author conbotngungoc
 */
class VehicleData {
    private String tenXe;
    private String hangXe;
    private String ngayGio;
    private double giaNhap;
    private boolean isMoi;

    // Constructors
    public VehicleData(String tenXe, String hangXe, String ngayGio, double giaNhap, boolean isMoi) {
        this.tenXe = tenXe;
        this.hangXe = hangXe;
        this.ngayGio = ngayGio;
        this.giaNhap = giaNhap;
        this.isMoi = isMoi;
    }

    // Getters and Setters (Alt + Insert in NetBeans to generate them)

    public String getTenXe() {
        return tenXe;
    }

    public void setTenXe(String tenXe) {
        this.tenXe = tenXe;
    }

    public String getHangXe() {
        return hangXe;
    }

    public void setHangXe(String hangXe) {
        this.hangXe = hangXe;
    }

    public String getNgayGio() {
        return ngayGio;
    }

    public void setNgayGio(String ngayGio) {
        this.ngayGio = ngayGio;
    }

    public double getGiaNhap() {
        return giaNhap;
    }

    public void setGiaNhap(double giaNhap) {
        this.giaNhap = giaNhap;
    }

    public boolean isMoi() {
        return isMoi;
    }

    public void setMoi(boolean moi) {
        isMoi = moi;
    }
}

public class input extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    ArrayList<VehicleData> vehicleList = new ArrayList<>();
    public input() {
        initComponents();
        setupTableListener();
    }
    private void setupTableListener() {
        jTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedRow = jTable.getSelectedRow();

                if (selectedRow != -1) {
                    // Hiển thị thông tin của hàng đã chọn
                    displaySelectedRowInfo(selectedRow);
                }
            }
        });
        jTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int selectedRow = jTable.getSelectedRow();
                if (selectedRow != -1) {
                    displaySelectedRowInfo(selectedRow);
                }
            }
        });
    }
    private void displaySelectedRowInfo(int selectedRow) {
        // Lấy thông tin của hàng đã chọn
        // Lấy thông tin của hàng đã chọn
        VehicleData selectedVehicle = vehicleList.get(selectedRow);

        // Hiển thị thông tin vào các ô tương ứng
        jtenxe.setText(selectedVehicle.getTenXe());
        jComboBox1.setSelectedItem(selectedVehicle.getHangXe());
        jngaygio.setText(selectedVehicle.getNgayGio());
        jgianhap.setValue(selectedVehicle.getGiaNhap());
        jCheckBox1.setSelected(selectedVehicle.isMoi());
        jCheckBox2.setSelected(!selectedVehicle.isMoi());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBack_input = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtenxe = new javax.swing.JFormattedTextField();
        jgianhap = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jthem = new javax.swing.JButton();
        jxoa = new javax.swing.JButton();
        capnhap = new javax.swing.JButton();
        jnhapmoi = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jngaygio = new javax.swing.JTextField();
        jaddoder = new javax.swing.JButton();
        jImport_input = new javax.swing.JButton();
        jExport_input = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("Input Vehicle data ");

        jBack_input.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jBack_input.setText("Back");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jBack_input, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(251, 251, 251))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(jBack_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );

        jTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "Tên Xe ", "Hãng xe ", "Ngày giờ", "Giá nhập", "Mới / Cũ"
                }
        ));
        jTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Tên xe");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Hãng xe");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ngày giờ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Giá nhập");

        jtenxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtenxeActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "Kia", "Mazda", "Ford", "Honda", "Vinfast", "Mec", "Audi", "BMW" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jthem.setText(" Thêm");
        jthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jthemActionPerformed(evt);
            }
        });

        jxoa.setText(" Xóa");
        jxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxoaActionPerformed(evt);
            }
        });

        capnhap.setText(" Cập nhập");
        capnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhapActionPerformed(evt);
            }
        });

        jnhapmoi.setText("Nhập mới");
        jnhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnhapmoiActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jCheckBox1.setText(" Mới");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jCheckBox2.setText(" Cũ");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jaddoder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jaddoder.setText("Add Oder");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jCheckBox1)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jgianhap)
                                                        .addComponent(jtenxe, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jngaygio)
                                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(51, 51, 51))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jthem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jxoa)
                                                .addGap(18, 18, 18)
                                                .addComponent(capnhap))
                                        .addComponent(jaddoder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jnhapmoi)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jtenxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBox1))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jngaygio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCheckBox1)
                                        .addComponent(jCheckBox2))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jthem)
                                        .addComponent(jxoa)
                                        .addComponent(capnhap)
                                        .addComponent(jnhapmoi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jaddoder, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jImport_input.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jImport_input.setText("Nhập dữ liệu");

        jExport_input.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jExport_input.setText("Xuất  dữ liệu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(235, 235, 235)
                                                .addComponent(jImport_input, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(230, 230, 230)
                                                .addComponent(jExport_input, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jImport_input, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jExport_input, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jtenxeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code he
    }
    private boolean isAlpha(String str) {
        return str.matches("^[a-zA-Z ]+$");
    }

    private void jthemActionPerformed(java.awt.event.ActionEvent evt) {
        String tenXe = jtenxe.getText();
        if (!isAlpha(tenXe)) {
            // Tên không hợp lệ, hiển thị thông báo lỗi
            JOptionPane.showMessageDialog(this, "Tên không hợp lệ! Hãy chỉ nhập chữ cái.");
            return;  // Thoát khỏi phương thức nếu tên không hợp lệ
        }
        String hangXe = jComboBox1.getSelectedItem().toString();


        String ngayGio = jngaygio.getText().trim();



        String giaNhapText = jgianhap.getText().replaceAll(",", "");

        // Kiểm tra nếu chuỗi không rỗng trước khi chuyển đổi
        if (!giaNhapText.isEmpty()) {
            try {
                double giaNhap = Double.parseDouble(giaNhapText);

                // Lấy giá trị của isMoi từ jCheckBox1.isSelected()
                boolean isMoi = jCheckBox1.isSelected();

                // Tạo một đối tượng VehicleData mới
                VehicleData newVehicle = new VehicleData(tenXe, hangXe, "", giaNhap, isMoi);

                // Thêm đối tượng vào ArrayList
                vehicleList.add(newVehicle);
                updateTable();
                JOptionPane.showMessageDialog(this, "Thêm mới thành công!");
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Lỗi: Giá nhập không hợp lệ!");
                ex.printStackTrace();  // In chi tiết lỗi vào console (hoặc thay thế bằng logging)
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Lỗi khi thêm mới: " + ex.getMessage());
                ex.printStackTrace();  // In chi tiết lỗi vào console (hoặc thay thế bằng logging)
            }
        } else {
            JOptionPane.showMessageDialog(this, "Lỗi: Vui lòng nhập giá nhập!");
        }
    }
    private void updateTable() {
        // Xóa tất cả các hàng hiện có trong bảng
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        model.setRowCount(0);

        // Thêm lại tất cả các dòng từ danh sách xe vào bảng
        for (VehicleData vehicle : vehicleList) {
            String loai = vehicle.isMoi() ? "mới" : "cũ" ;
            Object[] rowData = {
                    vehicle.getTenXe(),
                    vehicle.getHangXe(),
                    vehicle.getNgayGio(),
                    vehicle.getGiaNhap(),
                    loai
            };
            model.addRow(rowData);
        }
    }


    private void jxoaActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = jTable.getSelectedRow();

        // Kiểm tra xem có dòng được chọn hay không
        if (selectedRow != -1) {
            // Xóa dòng được chọn từ danh sách
            vehicleList.remove(selectedRow);

            // Cập nhật bảng
            updateTable();
        } else {
            // Hiển thị thông báo nếu không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }


    private void capnhapActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = jTable.getSelectedRow();

        if (selectedRow != -1) {
            // Lấy thông tin từ các ô đầu vào
            String tenXe = jtenxe.getText();
            String hangXe = jComboBox1.getSelectedItem().toString();
            String ngayGio = jngaygio.getText();
            double giaNhap = Double.parseDouble(jgianhap.getText().replaceAll(",", ""));
            boolean isMoi = jCheckBox1.isSelected();

            // Cập nhật thông tin của hàng đã chọn trong ArrayList
            VehicleData selectedVehicle = vehicleList.get(selectedRow);
            selectedVehicle.setTenXe(tenXe);
            selectedVehicle.setHangXe(hangXe);
            selectedVehicle.setNgayGio(ngayGio);
            selectedVehicle.setGiaNhap(giaNhap);
            selectedVehicle.setMoi(isMoi);

            // Cập nhật bảng
            updateTable();

            // Hiển thị thông báo cập nhật thành công
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } else {
            // Hiển thị thông báo nếu không có dòng nào được chọn
            JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để cập nhật.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void jnhapmoiActionPerformed(java.awt.event.ActionEvent evt) {
        // Xóa nội dung trong các ô đầu vào
        jtenxe.setText("");
        jComboBox1.setSelectedIndex(0); // Chọn mục đầu tiên trong danh sách
        jgianhap.setValue(0.0); // Đặt giá trị mặc định hoặc có thể để trống tùy thuộc vào yêu cầu
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
    }

    private void jCheckBox1ActionPerformed (java.awt.event.ActionEvent evt) {

        if (jCheckBox1.isSelected()) {
            jCheckBox2.setSelected(false);
        }
    }

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (jCheckBox2.isSelected()) {
            jCheckBox1.setSelected(false);
        }
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton capnhap;
    private javax.swing.JButton jBack_input;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JButton jExport_input;
    private javax.swing.JButton jImport_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jaddoder;
    private javax.swing.JFormattedTextField jgianhap;
    private javax.swing.JTextField jngaygio;
    private javax.swing.JButton jnhapmoi;
    private javax.swing.JFormattedTextField jtenxe;
    private javax.swing.JButton jthem;
    private javax.swing.JButton jxoa;
    // End of variables declaration
}
